print("Good afternoon world!")
print("Today is Friday the 20th.")
print("I have completed all of my classes for this week.")
print("The only thing that entails for the rest of this day is my 100 homework assignments.")
print("I am hoping to try to order food today, and am praying that the delivery fee is less than $10.")
print("I don't want to spend more than $20, so if the fee is $10, that's 50% of the food total!")
print("The rest of my weekend is looking calm, I want to attend the devotional on Saturday, I heard there will be food there.")
print("Sunday should be nothing but church, I should call my mom pretty soon though, she tends to worry.")
print("Then later on Monday, I only have one class, and that's my New Testament class, we're reading in Matthew 7-11 next week.")
print("I am loving my schedule so far, even my late class, that ends at 10:15PM, although that on makes me exhausted.")