#print("How much wood could a woodchuck chuck if a woodchuck could chuck wood?")
#print("I don't know man, how much wood could a woodchuck chuck if a woodchuck could chuck wood?")
#print("A woodchuck could chuck about 12 wood.")
import time

player = input("What's your name player? ")
time.sleep(1)
print(f"Ah! I knew a {player} once, they were kind of a weirdo.")
time.sleep(1)
height = float(input("And how tall are you? "))

time.sleep(1)
if height <= 5.69:
    print(f"{height} Are you sure you're not a hobbit?")
elif 5.7 <= height <= 5.99:
    print(f"{height}! What a marvelous height!")
if height >= 6.0 >=7.0:
    print(f"{height}!! Oh we have a giant aye?!")
elif height >= 7.01:
    print(f"{height}...Is that even possible?")

time.sleep(1)
gender = input("Finally, what are you, a man or a woman? ")
time.sleep(1)
if gender in ["man", "Man", "male", "Male", "guy", "boy"]:
    print("A man! Good to know.")
elif gender in ["woman", "Woman", "female", "Female", "girl"]:
    print("A woman! Good to know.")
else:
    print("Well... moving on then.")
    

time.sleep(1)
print(f"Now {player}, let's begin this journey, we start things as all good stories do, you have awoken in bed.")
time.sleep(1)
print("Now here is your first choice of the day, (1) get up or (2) turn right over? ")
choice_1 = int(input("Option 1 or Option 2? "))
if choice_1 == 1:
    time.sleep(3)
    print("You have gotten up and stretched your arms out, you feel a slight pull and then a burning feeling.")
    time.sleep(3)
    print("You have hurt your shoulder! Do you want to (1) go to the doctor, or (2) ignore it and move on? ")
    choice_1a = int(input("Option 1 or Option 2? "))
    if choice_1a == 1:
        print("You grab your car keys, time to head over to the doctors.")
        time.sleep(3)
        print("You're driving down, you can either go the (1) freeway or the (2) back roads, they will take the same amount of time.")
        choice_1aa = int(input("Option 1 or Option 2? "))
        if choice_1aa == 1:
            print("You take the freeway! A bit dangerous aye?")
            time.sleep(3)
            print("Or not! I really thought something would've happened. You arrive safely at the doctors and walk in.")
            time.sleep(3)
            print("You talk to the nice receptionist, they seem fun, I saw you blushing, don't lie to me :)")
            time.sleep(3)
            print("Now you are sitting down waiting, the pain seems to have died down a little bit but is still there.")
            time.sleep(3)
            print("And you're waiting.")
            time.sleep(3)
            print("And waiting..")
            time.sleep(3)
            print("And waiting...")
            time.sleep(3)
            print("OK, this is ridiculous, how are you so patient? I'm upset for you.")
            time.sleep(3)
            print("Why are you still waiting? Seriously, do something.")
            time.sleep(3)
            print("Are you really not going to do anything?")
            time.sleep(3)
            print("Get up!!")
            time.sleep(3)
            print("Oh wait... I'm supposed to give you you're options, that one's on me.")
            time.sleep(3)
            print("You're growing impatient, you decide you want to either (1) talk to the receptionist again, or (2) just leave and go back home.")
            choice_1aaa = int(input("Option 1 or Option 2"))
            if choice_1aaa == 1:
                time.sleep(3)
                print("I knew you liked them! You go walk over to the receptionist.")
                time.sleep(3)
                print("Well that was a 'friendly' conversation, she was very helpful and said the doctor will see you in 5 minutes.")
                time.sleep(3)
                print("Seriously, you should go talk to them again, I know they were feeling it too.")
                time.sleep(3)
                print("Wah wah about your shoulder, go taaaaaalk to them, please.")
                time.sleep(3)
                print("For my entertainment.")
                time.sleep(3)
                print("Ugh fine, you got lucky, the doctor walks out and brings you back.")
                time.sleep(3)
                print("He looks at your shoulder, a pulled muscle, you really went all the way to the doctor for a pulled muscle? Toughen up geez.")
                time.sleep(3)
                print("Welp, you walked out the office, with the advice of icing it and resting, Google could've told you that...")
                time.sleep(3)
                print("You drive home, now do you want to go back through the (1) freeway, or (2) the back roads?")
                choice_1aaaa = int(input("Option 1 or Option 2? "))
                if choice_1aaaa == 1:
                    time.sleep(3)
                    print("Ah! The same way! Hopefully something will happen this time!")
                    time.sleep(3)
                    print("...")
                    time.sleep(3)
                    print("Or not again. Wow, you are a good driver I guess.")
                    time.sleep(3)
                    print("Well now you're home, and have done absolutely nothing. *grumble* Somebody is hungry.")
                    time.sleep(3)
                    print("You want to eat? Fine, here's your options.")
                    time.sleep(3)
                    print("You can either (1) cook your own food, or (2) order food, heard there's a good Mexican place down the road.")
                    choice_1aaaaa = int(input("Option 1 or Option 2? "))
                    if choice_1aaaaa == 1:
                        time.sleep(3)
                        print("Yes! Please be a fire, that'll actually be exciting! What're you making? Burnt eggs? Burnt steak? Burnt toast? The possibilities are endless!")
                        time.sleep(3)
                        print("...cold old pizza...")
                        time.sleep(3)
                        print("You know, when I said COOK your own food, I did not mean leftovers.")
                        time.sleep(3)
                        print("Gosh you're so boring...")
                        time.sleep(3)
                        print("Oh would you look at the time, time for you to... log into...")
                        if gender in ["woman", "Woman", "female", "Female", "girl"]:
                            print("Amazon? You have no money though!")
                        elif gender in ["man", "Man", "male", "Male", "guy", "boy"]:
                            print("Crypto?! Oh my goodness, you're a crypto bro, I knew it, that's why you're so boring.")
                        time.sleep(3)
                        print("This is so boring...")
                        time.sleep(3)
                        print("Welp, do you want another decision? You're probably just going to pick the boring option anyways")
                        time.sleep(3)
                        print("Fine, uhhhhhmmmmm...")
                        time.sleep(3)
                        print("Do you want (1) to go to bed, or (2) watch a movie")
                        choice_1aaaaaa = int(input("Option 1 or Option 2?" ))
                        if choice_1aaaaaa == 1:
                            print("Of course you picked that option, why wouldn't you.")
                            time.sleep(3)
                            print("Alright, you go to bed, and you fall asleep.")
                            time.sleep(3)
                            print("THE END")
                            time.sleep(1)
                            print("SCORE: BORING")
                            #figure out way to loop it back to the beginning
                            #start option 2 from down up
